### ISSUE TITLE
Not All React's Hooks Are Implemented

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#203]
Not all of [React's builtin](https://reactjs.org/docs/hooks-reference.html) hooks have been implemented. If you have a pressing need for a missing hook leave a comment here.

- [x] `use_state`
- [x] `use_effect`
- [x] `use_context`
- [x] `use_reducer`
- [x] `use_callback`
- [x] `use_memo`
- [x] `use_ref`
- [x] `use_debug_value`

**Comment by Archmonger** [comment]
@rmorshea Which hooks are still under development?

**Comment by rmorshea** [comment]
I think the only one not implemented at this point is `useContext`.

**Comment by rmorshea** [comment]
This is done now!
