### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by researchase** [idom-team/idom#306]
**Bug description**
unable to install material_ui as instructed in the tutorial 
import idom
material_ui = idom.install("@material-ui/core")
# or install multiple modules at once

getting the following error : 

2021-02-27 23:13:53.255 | INFO     | idom.client.manage:build:105 - Installing ['@material-ui/core', 'idom-client-react@^0.7.3', 'react@^16.13.1', 'react-dom@^16.13.1'] ...
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/idom/client/manage.py in _run_subprocess(args, cwd)
    143     try:
--> 144         subprocess.run(
    145             [which_cmd] + args,

/usr/lib/python3.8/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    511         if check and retcode:
--> 512             raise CalledProcessError(retcode, process.args,
    513                                      output=stdout, stderr=stderr)

CalledProcessError: Command '['/usr/bin/npm', 'install', '@material-ui/core', 'idom-client-react@^0.7.3', 'react@^16.13.1', 'react-dom@^16.13.1']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

SubprocessError                           Traceback (most recent call last)
<ipython-input-3-c78d91c3f710> in <module>
      1 import idom
----> 2 material_ui = idom.install("@material-ui/core")
      3 # or install multiple modules at once
      4 material_ui, *other_modules = idom.install(["@material-ui/core", ...])

/usr/local/lib/python3.8/dist-packages/idom/client/module.py in install(packages, ignore_installed, fallback)
     40 
     41     if ignore_installed or pkg_names.difference(manage.web_module_names()):
---> 42         manage.build(packages)
     43 
     44     return (

/usr/local/lib/python3.8/dist-packages/idom/client/manage.py in build(packages_to_install, clean_build)
    104 
    105         logger.info(f"Installing {packages_to_install or 'packages'} ...", debug=True)
--> 106         _npm_install(packages_to_install, temp_app_dir)
    107         logger.info("Installed successfully ✅")
    108 

/usr/local/lib/python3.8/dist-packages/idom/client/manage.py in _npm_install(packages, cwd)
    127 
    128 def _npm_install(packages: List[str], cwd: Path) -> None:
--> 129     _run_subprocess(["npm", "install"] + packages, cwd)
    130 
    131 

/usr/local/lib/python3.8/dist-packages/idom/client/manage.py in _run_subprocess(args, cwd)
    150         )
    151     except subprocess.CalledProcessError as error:  # pragma: no cover
--> 152         raise subprocess.SubprocessError(error.stderr.decode()) from error
    153     return None

SubprocessError: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/tmp/tmplgg9_ncw/app/node_modules/esbuild/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.6.34 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esbuild@0.6.34 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-27T17_43_57_626Z-debug.log
**To reproduce**

1. ... using ubuntu 20.10
2. ...using jupyterlab v3 
3. ...

**Expected behavior**
I was hoping that I can use material-ui 
**Screenshots**

**Additional context**

**Comment by rmorshea** [comment]
Thanks for reporting. I'll get to this soon.

**Comment by researchase** [comment]
@rmorshea I had install idom using sudo pip install , I uninstalled it and tried just pip install idom and the demo worked !! not sure why. I think this can be closed
