### ISSUE TITLE
Print the URL when using idom.run

### ISSUE THREAD

**Issue by stevenheidel** [idom-team/idom#322]
**Is your feature request related to a problem? Please describe.**

Right now when using `idom.run` the port argument defaults to a dynamically discovered port. Nothing printed to the screen so I did not know how to access the site.l

**Describe the solution you'd like**

Print a message like: "View page at localhost:port/client/index.html" or just open the page automatically in a browser

**Describe alternatives you've considered**

For now I just hardcode the port to 8765

**Comment by rmorshea** [comment]
I think you're running the Flask server, which does have this problem. `idom.run` tries to find the first supported server implementation based on what's installed in your environment. Given that, `idom.run` should also log which implementation it's using.
