### ISSUE TITLE
add VDOM to HTML util function

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#435]
Sample implementation:

```python
from html import escape as html_escape

def vdom_to_html(vdom: Union[str, VdomDict]) -> str:
    """Convert a VDOM dictionary into an HTML string

    Only the following keys are translated to HTML:

    - ``tagName``
    - ``attributes``
    - ``children`` (must be strings or more VDOM dicts)
    """
    if isinstance(vdom, str):
        return vdom

    try:
        tag = vdom["tagName"]
    except TypeError as error:
        raise TypeError(f"Expected a VDOM dictionary or string, not {vdom}") from error

    if "attributes" in vdom:
        attributes = " " + " ".join(
            f'{k}="{html_escape(v)}"' for k, v in vdom["attributes"].items()
        )
    else:
        attributes = ""

    if "children" in vdom:
        children = "".join(map(vdom_to_html, vdom["children"]))
    else:
        children = ""

    return f"<{tag}{attributes}>{children}</{tag}>"
```

**Comment by rmorshea** [comment]
@Archmonger there's the function.

**Comment by Archmonger** [comment]
I believe I was looking for the inverse of this. Would be useful for Django purposes (ex. render via Django template, push template into IDOM).

**Comment by rmorshea** [comment]
That actually exists 🙂: [`html_to_vdom`](http://idom-docs.herokuapp.com/docs/auto/api-reference.html?highlight=html_to_vdom#idom.utils.html_to_vdom)

**Comment by Archmonger** [comment]
Yep, but if I recall the conservation was brought up in reference to it not being documented.

**Comment by rmorshea** [comment]
The documentation is linked to above. Maybe I'm misunderstanding?

**Comment by Archmonger** [comment]
Oh that's my bad. I must have missed it when scrolling through the docs.

**Comment by rmorshea** [comment]
@acivitillo, if you want to use IDOM for HTML templating, this might be a good thing to try contributing.
