### ISSUE TITLE
JS issue when using with @blueprintjs/core package

### ISSUE THREAD

**Issue by rafaellichen** [idom-team/idom#453]
### Discussed in https://github.com/idom-team/idom/discussions/452

<div type='discussions-op-text'>

<sup>Originally posted by **rafaellichen** July 28, 2021</sup>
Related issue ticket: https://github.com/palantir/blueprint/issues/4823
I tried to use @blueprintjs/core to render a button in the jupyter notebook with idom, but that results in js error in the browser console.
```python
import idom
import idom_jupyter

blueprintjs = idom.web.module_from_template("react", "@blueprintjs/core", fallback="...")
bpbutton = idom.web.export(blueprintjs, "Button")

@idom.component
def ShowButton():
    return bpbutton()

ShowButton()
```
Tested using this environment: https://mybinder.org/v2/gh/idom-team/idom-jupyter/main?filepath=notebooks%2Fintroduction.ipynb

In the browser console, error: Uncaught (in promise) SyntaxError: Invalid or unexpected token
The error originates from the linked file core.js on: https://cdn.esm.sh/v43/@blueprintjs/core@3.47.0/es2020/core.js
Use text search to find the only code starting with 1.tolocal or t=1; this is where the error starts.
</div>

---
I still think it's syntax issue in the core.js file.Any other opinions?

**Comment by rafaellichen** [comment]
it seems like a regular JS issue, but that piece of code looks syntactically correct as calling `toLocaleString` on a number is possible (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)

**Comment by rmorshea** [comment]
I'm going to close this in favor of the discussion for now. I'll recreate or reopen this issue once we determine what action needs to be taken in order to resolve the issue.

**Comment by rafaellichen** [comment]
@rmorshea resolved by changing package build method
