### ISSUE TITLE
Serialize Form Data

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#573]
### Current Situation

Currently, `onSubmit` events for `form` elements do not serialize the data contained within them. To do this we need to serialize the `form.elements` attribute. 

### Proposed Changes

```
diff --git a/src/client/packages/idom-client-react/src/event-to-object.js b/src/client/packages/idom-client-react/src/event-to-object.js
index b11e653..80b098b 100644
--- a/src/client/packages/idom-client-react/src/event-to-object.js
+++ b/src/client/packages/idom-client-react/src/event-to-object.js
@@ -49,6 +49,13 @@ const elementTransformCategories = {
       return {};
     }
   },
+  hasElements: (element) => {
+    const result = {};
+    for (key in element.elements) {
+      result[key] = serializeDomElement(element.elements[key]);
+    }
+    return result;
+  }
 };
 
 function defaultElementTransform(element) {
@@ -69,6 +76,7 @@ const elementTagCategories = {
   ],
   hasCurrentTime: ["AUDIO", "VIDEO"],
   hasFiles: ["INPUT"],
+  hasElements: ["FORM"],
 };
 
 const elementTransforms = {};
```

**Comment by Archmonger** [comment]
There's going to need to be considerations made for file fields. We're also going to need to make [considerations related to backpressure](https://web.dev/websocketstream/), especially since there's the potential to upload files with an uncapped size.

Probably worth generalizing the data serialization (perhaps even as a separate package?). If it's generic enough, there's a possibility that down the line it would allow for using the WS to stream video.

**Comment by rmorshea** [comment]
I think there's an issue (or discussion) about serializing files.

Could you make file serialization into an issue if it isn't one and create an separate issue for dealing with back-pressure?

**Comment by rmorshea** [comment]
@acivitillo this seems like a less-trivial first issue.

**Comment by Archmonger** [comment]
File serialization issue appears to exist: https://github.com/idom-team/idom/issues/574

Shouldn't backpressure be handled within the file serialization issue? Feels strange creating a new issue to handle an _not yet developed_ limitation.

**Comment by rmorshea** [comment]
I think back-pressure is a general problem. Any event, not just those with files, could take a long time for the network to send and the server to process which would thus cause things to back up.

**Comment by Archmonger** [comment]
Something else I'm generally thinking about on this PR is there's going to need to be some degree of consideration for Django here.

Django forms have a validator function that is run to verify the form's data. I'm not sure how we'd work that in to an "IDOM form"...

Maybe we need some sort of concept of form middleware? Would also need some class mixins within Django IDOM, most likely.

**Comment by acivitillo** [comment]
Well, from my end I can take a stab at the initial PR idea, but I am not sure if I can also consider all the other cases. Could we implement form serialization incrementally via multiple PRs?

**Comment by Archmonger** [comment]
Yeah it can be handled incrementally.

**Comment by acivitillo** [comment]
ok so I started working on this, there is a problem with keys. This is because a form can have an indefinite number of elements, so `target` will be a json of multiple targets. 

We can go with index keys, but then I need to understand how to build a test case for `FORM` in `event-to-object.test.js`

```javascript
  hasElements: (element) => {
    const result = {};
    Object.keys(element).forEach((key) => {
      result[key] = serializeDomElement(element.elements[key])
    });
    return result;
  }
```

gives the below json

```json
{
  "target": {
    "0": {
      "boundingClientRect": {
        "x": 8,
        "y": 8,
        "width": 149,
        "height": 22,
        "top": 8,
        "right": 157,
        "bottom": 30,
        "left": 8
      },
      "value": ""
    },
    "1": {
      "boundingClientRect": {
        "x": 8,
        "y": 80,
        "width": 52,
        "height": 22,
        "top": 80,
        "right": 60,
        "bottom": 102,
        "left": 8
      },
      "value": "Submit"
    },
    "2": {
      "boundingClientRect": {
        "x": 60,
        "y": 80,
        "width": 149,
        "height": 22,
        "top": 80,
        "right": 209,
        "bottom": 102,
        "left": 60
      },
      "value": ""
    },
    "boundingClientRect": {
      "x": 8,
      "y": 8,
      "width": 408,
      "height": 128,
      "top": 8,
      "right": 416,
      "bottom": 136,
      "left": 8
    },
    "__reactInternalInstance$6poh51syf6f": null,
    "__reactEventHandlers$6poh51syf6f": null
  },
  "currentTarget": {
    "0": {
      "boundingClientRect": {
        "x": 8,
        "y": 8,
        "width": 149,
        "height": 22,
        "top": 8,
        "right": 157,
        "bottom": 30,
        "left": 8
      },
      "value": ""
    },
    "1": {
      "boundingClientRect": {
        "x": 8,
        "y": 80,
        "width": 52,
        "height": 22,
        "top": 80,
        "right": 60,
        "bottom": 102,
        "left": 8
      },
      "value": "Submit"
    },
    "2": {
      "boundingClientRect": {
        "x": 60,
        "y": 80,
        "width": 149,
        "height": 22,
        "top": 80,
        "right": 209,
        "bottom": 102,
        "left": 60
      },
      "value": ""
    },
    "boundingClientRect": {
      "x": 8,
      "y": 8,
      "width": 408,
      "height": 128,
      "top": 8,
      "right": 416,
      "bottom": 136,
      "left": 8
    },
    "__reactInternalInstance$6poh51syf6f": null,
    "__reactEventHandlers$6poh51syf6f": null
  },
  "relatedTarget": null
}
```

**Comment by acivitillo** [comment]
I tried playing with a `FORM` test case but I get `Cannot read property 'tagName' of undefined`

```javascript
  ...["AUDIO", "VIDEO"].map((tagName) => ({
    case: `adds 'currentTime' attribute for ${tagName} element`,
    tagName,
    output: { target: { currentTime: allTargetData.currentTime } },
  })),
  ...["FORM"].map((tagName) => ({
    case: `adds 'value' attribute for ${tagName} element`,
    tagName,
    output: { target: { value: allTargetData.value } },
  })),
```

**Comment by rmorshea** [comment]
Can you put up PR so I can look at the diff?

**Comment by acivitillo** [comment]
https://github.com/idom-team/idom/pull/699/files#diff-3f303c8e01a070d03f718729164a7cfefc2d103cb460777a178d35c11ac99169
