### ISSUE TITLE
Add SVG Elements to HTML Module

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#576]
### Current Situation

We don't have a builtin function for creating standard SVG elements.

### Proposed Actions

Add them to the `idom.html` module

**Comment by acivitillo** [comment]
I would also add your point on `idom.vdom(tag, ...)` to the *HTML with IDOM* docs. If you agree I can send you a PR when I get the time.

**Comment by rmorshea** [comment]
That would be great!
