### ISSUE TITLE
render_jsx() Function

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#577]
### Current Situation

In order to render JSX, currently custom components are needed.

### Proposed Actions

Create an `idom.jsx.render` function that can output JSX to VDOM.

See [python-react](https://github.com/markfinger/python-react#python-react) for design inspiration.

### Implementation Details

The interface would look something like this...

```python
@idom.component
def my_component():
    return idom.jsx.render("/path/to/component.jsx", {"foo":"bar"})

@idom.component
def my_second_component():
    # Also, we should try to make it play nicely with standard IDOM templating
    return h1(
        "Hello World",
         idom.jsx.render("/path/to/component.jsx",
         {"foo":"bar"},
         ),    
    )
```

It may be worthwhile to look at [`v8-cffi`](https://github.com/nitely/v8-cffi), [`v8eval`](https://github.com/sony/v8eval), or [`react-render`](https://github.com/mic159/react-render) for server side rendering of React components.

**Comment by Archmonger** [comment]
This would be an amazingly useful developer utility that would effectively make custom components obsolete.
But as of right now is not a MVP feature. So I think it belongs in v1.

**Comment by Archmonger** [comment]
@rmorshea Also I'm realizing the awkwardness of the GitHub projects titles.

It's hard to tell if `1.x Release` means that all of those features are required to reach V1, or if those tasks will be developed while in V1.

**Comment by rmorshea** [comment]
I think this can probably be wrapped up in the #578 issue. Ultimately there may be different ways of doing server-side rendering in IDOM, but at least to start, we'll probably want to just pick one.

**Comment by Archmonger** [comment]
JSX rendering can be done in multiple ways, and can possibly be server side render or client side.

I'm thinking of this specific ticket as a "custom components 2.0"

**Comment by rmorshea** [comment]
The custom components interface is a bit more general than this. It doesn't make assumptions about how the components are implemented - it might be React, but it doesn't have to be. Thus, a feature like this would probably be implemented as a custom component that reaches out to react render server endpoint.
