### ISSUE TITLE
State mismatch during component update

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#629]
### Current Situation

Currently, updating any child component state can result in `AssertionError: state mismatch during component update - key '61e47127-9d3f-4954-8235-4d99122134c1'!=4`

This can be previewed within Conreq's app store branch.

### Proposed Actions

Update `layout.py` to not cause this exception.

### Work Items

- [ ] Develop a fix for state mismatch
- [ ] Release 0.35.5 to resolve this

**Comment by rmorshea** [comment]
Ok, this isn't as bad as I thought. This assertion should just be removed entirely.

**Comment by Archmonger** [comment]
Confirmed removing the assertion fixes the issue and causes no visible consequences.

**Comment by Archmonger** [comment]
Also, this issue is more of a P0 than a P1, since it fundamentally breaks IDOM
