### ISSUE TITLE
Reconsider how we use/advertise idom.run()

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#657]
### Current Situation

`idom.run()` probably shouldn't be the primary advertised way of using IDOM. Especially in it's current state.

Using a development webserver for production use is a big no-no, and by prominently displaying `idom.run()` as the first steps to using IDOM shows we are encouraging people to do just that. I believe the primary way of utilizing IDOM should be embedding within existing applications.

- #654

### Proposed Actions

- [ ] Keep `idom.run()` as is, but add logging to indicate `idom.run()` is not suited for production use.
   - ex. `idom.run() is only intended for testing purposes. For production use, consider embedding IDOM within an existing project. Check out the docs for more info.`
- [ ] Expand the ease-of-use for integrating into supported web frameworks, similar to Django-IDOM
   - #653
- [ ] Remove SharedClientState, as it is not compatible with multiprocessed webservers.
   - This is also an opportunity to rename `PerClientState` to `IdomView` 

#### Optional
- Change the callable name/path to more appropriately indicate **danger** or **for testing purposes only**
   - `idom.testing.webserver()`
   - `idom.shortcuts.run()`
   - `idom.devtools.run_webserver()`
- Remove the pip parameter for frameworks (it's really not needed)
   - `idom.run()` should raise a simple to understand exception if the user has forgotten to install a web framework
   - ex. `Looks like you don't have a web framework installed. You'll need to pip install one of the following: fastapi, flask, sanic`

**Comment by Archmonger** [comment]
My personal opinion is that `idom.run()` should be tucked away into a "dev tools" closet as-is and shouldn't be prominently advertised.

Instead, we should focus on simplifying how users integrate IDOM into existing applications.

**Comment by rmorshea** [comment]
We could add a big fat warning about this instead? Technically doing `idom.run` is fine with Sanic (and I think Tornado too), but not  the others.

**Comment by rmorshea** [comment]
Meh, nevermind. We should completely shift how this works:

- Drop the run function
- stop calling things a per-client state "server" and instead call it a "view"
- Make `app` a required argument of `PerClientStateView` etc.

Doing this with appropriate deprecation warnings will be a bit tricky, but I think that sends a more accurate message about how you should expect to use IDOM.

**Comment by rmorshea** [comment]
The only question then is how you many the "hello world" still look simple...

**Comment by rmorshea** [comment]
Maybe do:

```python
from idom import component, html, server


@component
def App():
    return html.h1("Hello, World!")


server.default.run(App)
```

Except `run` only accepts one argument (use lack of configuration as deterrent) and produces a big fat warning.

**Comment by rmorshea** [comment]
There's also a question of the install target: https://github.com/idom-team/idom/issues/600

I think we should we remove any sense of a "default" install target too since you'd always need to explicitly call out which server implementation you're using.

**Comment by Archmonger** [comment]
> Doing this with appropriate deprecation warnings will be a bit tricky, but I think that sends a more accurate message about how you should expect to use IDOM.

IDOM is still <v1.0.0, technically we've never needed to deprecate anything. Immediate breaking changes are fully acceptable on pre-release version numbers.

> The only question then is how you many the "hello world" still look simple...

Maybe we consider a pattern like this (with the run callable name being TBD)

```python 
from idom import component, html, devtools
from fastapi import FastAPI

fastapi_app = FastAPI()

@component
def Hello():
    return html.h1("Hello, World!")

# This should print a warning that it is not production usable
devtools.run(fastapi_app, component=Hello)
```

**Comment by rmorshea** [comment]
I'm worried about the hello-world implying a preference for a given server implementation.

**Comment by Archmonger** [comment]
That's pretty much an impossible problem to solve without just duplicating the examples. We support multiple web frameworks, but we need to choose at least one to first demo with. 

Could just be a comment saying "Utilize whatever Python web framework you like here!"

**Comment by Archmonger** [comment]
> - stop calling things a per-client state "server" and instead call it a "view"
> - Make app a required argument of PerClientStateView etc.
> - Rename idom.server.proto.ServerType.run to run_dev_server

That's a good first step. This actually brings up another thing I've forgotten to mention. I _really dislike_ the name `PerClientState<X>`. It's really hard to tell what it does based on that name.

**Comment by Archmonger** [comment]
> I think we should we remove any sense of a "default" install target too since you'd always need to explicitly call out which server implementation you're using.

I also agree with this. It's best for us to not dictate what gets used.

In that case, we really don't need a parameter at all. We can just say it's up to them to separately install a web framework, similar to how [whitenoise](https://github.com/evansd/whitenoise) has no Flask/FastAPI/Django/etc pip parameters,

**Comment by rmorshea** [comment]
> In that case, we really don't need a parameter at all.

True

**Comment by rmorshea** [comment]
> I really dislike the name PerClientState<X>

I've gotten an inverse comment at some point. With that said, I had a hard time coming up with a name that accurately described what they did so I'd be open to suggestions.

**Comment by rmorshea** [comment]
> IDOM is still <1.0.0, technically we've never needed to deprecate anything.

I feel some obligation to make things easier on early adopters where possible.

**Comment by Archmonger** [comment]
Based on your your thoughts above, I think I've come up with the best solution for everyone.

### Implement all of the following within one PR

1) Keep `idom.run()` as is, but add logging to indicate `idom.run()` is not suited for production use, and developers should look into embedding IDOM into an existing WSGI/ASGI application.
   - We'd also need to expand the docs to add clear steps for each supported web framework
2) Remove the pip parameter for frameworks (it's really not needed)
3) `idom.run()` will continue to automatically look for any installed server implementations, and will raise a more simple to understand exception if the user has forgotten to install a web framework
   - ex. `Looks like you don't have a web framework installed. You'll need to pip install one of the following: fastapi, flask, sanic`
4) Expand the ease-of-use for integrating into supported web frameworks, similar to Django-IDOM
   - #653

Optionally:
- Change the callable name/path to more appropriately indicate **DANGER** or **FOR QUICK TESTING ONLY**

**Comment by Archmonger** [comment]
> > I really dislike the name PerClientState
> 
> I've gotten an inverse comment at some point. With that said, I had a hard time coming up with a name that accurately described what they did so I'd be open to suggestions.

Just removing `State` from the name makes it a lot easier to understand. For example `PerClientView` .

**Comment by Archmonger** [comment]
Let me know if you agree on https://github.com/idom-team/idom/issues/657#issuecomment-1032354703

**Comment by rmorshea** [comment]
I think this issue may be related: https://github.com/idom-team/idom/issues/653

**Comment by rmorshea** [comment]
Ah, whoops, didn't read through your comment.

Yes, I think I agree.

**Comment by rmorshea** [comment]
Probably with the addition that `idom.run` takes a single argument (the component) to discourage use in the long term.

**Comment by Archmonger** [comment]
How do you feel about removing SharedView? https://github.com/idom-team/idom/issues/657#issuecomment-1032359747

**Comment by rmorshea** [comment]
I agree
