### ISSUE TITLE
Input's onChange Event Handler Misses Key Strokes?

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#684]
### Discussed in https://github.com/idom-team/idom/discussions/668

<div type='discussions-op-text'>

<sup>Originally posted by **jkrobicki** February 14, 2022</sup>
Description
When I fill in the input fast it reacts slowly and miss some letters. In the example I try to write "write here the name" .
![name iput](https://user-images.githubusercontent.com/88193723/153855377-07ef4bd0-a1e0-4940-adf7-8a7dbd5bba28.gif)
</div>

**Comment by rmorshea** [comment]
#694 does not appear to have fixed this issue.

**Comment by Archmonger** [comment]
My opinion is that if this limitation exists within React, there isn't a major reason to resolve this limitation within v1.

**Comment by rmorshea** [comment]
That's what I thought, but this is only problematic for React in the case where the onChange handler responds asynchronously. When the handling is sync, then everything works.

**Comment by Archmonger** [comment]
Do we handle this situation correctly if binding a sync IDOM event handler?

**Comment by rmorshea** [comment]
Only React behaves correctly in that circumstance.

The issue is unrelated to the server-side event handler. This has to do with the fact that the server's response to an event is async - the fact that, to trigger a re-render, we have to go to a websocket and asynchronously await a response from the server is analogous to the [case where React has problems](https://jsfiddle.net/1e9y48gr/2/).

**Comment by Archmonger** [comment]
Would buffering received events help mitigate this?

**Comment by rmorshea** [comment]
The real way to do this would be to block the client or buffer future events until the server finished handling the current event.

**Comment by rmorshea** [comment]
Actually, that wouldn't work... I'm not really sure there's a great way to solve this perfectly. The PR I just put up solves it for probably 95% of cases, but it has some pitfalls. For example, if the server modifies the input's value in any way (e.g. server-side auto-correct or something) then this problem pops up again.

**Comment by rmorshea** [comment]
That wouldn't really solve the problem. We'd have to buffer until the server responded with the next render before sending the next event. That doesn't work though since the server doesn't have to respond to events at all. That is, we don't strictly have to alternate between render, event, render, event, ...

I think I've found a way to solve this a different way though in #696

**Comment by rmorshea** [comment]
I'm still observing some weird flicker in Brave, but Chrome and Firefox seem to work fine. Not quite sure why.
