### ISSUE TITLE
Refactor Code and Docs "Server" Verbiage

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#720]
### Current Situation

There are a lot of locations in the source & docs where we currently call things "server", when they really should be called "web frameworks"

### Proposed Actions

Rename functions, comments, and docs while keeping these guidelines in mind

- Web Framework = FastAPI, Flask, Sanic, Tornado, Django
- Web Server = Gunicorn, Uvicorn, Hypercorn, Daphne, Built-in development servers, etc
- Reactive Component Framework = IDOM
   - It's an easier way to distinguish us rather than the more literal "we are a web framework built on-top of web frameworks"
- Views = Built-ins that assist in plopping something visual onto the page
- Components = We are already pretty good about the usage of "component", no need for change

**Comment by rmorshea** [comment]
I basically agree and was thinking about this in my last PR. Only difference is that maybe we could use "Web Application" instead of "Web Framework". Framework is a but generic - one could have frameworks for building both apps and servers.

**Comment by Archmonger** [comment]
I haven't given much thought on what we could rename idom.server to.

Maybe `idom.compat`?

I'm currently on vacation, I'll give more thought to this next week.

**Comment by Archmonger** [comment]
I'll likely update this list if I think of more. But this is what I have for now:

1) `idom.compat`
2) `idom.compatbility`
3) `idom.frameworks`
4) `idom.support`
5) `idom.backends`
6) `idom.conf`

**Comment by rmorshea** [comment]
I'm thinking `idom.app` might be fine. Whenever you construct something like `flask.Flask` or `sanic.Sanic` all the examples [assign to an `app` variable](https://flask.palletsprojects.com/en/2.1.x/quickstart/#a-minimal-application).

**Comment by rmorshea** [comment]
We should be able to use the same language as these app frameworks do.

**Comment by Archmonger** [comment]
In those contexts app = WSGI/ASGI application. The end user isn't really directly interfacing with the WSGI/ASGI app through IDOM. Instead, they're accessing HTTP/WS requests within a specific lifecycle.

At the same time, I'm personally not a big fan of any of the options I posted.

I'd think of it from a few steps back. What is it that the module currently trying to do, and what might it do in the future? From my perspective:
- Provide helper functions specific limited to our supported web frameworks
- Provide scoped access to WS/HTTP functionality

**Comment by rmorshea** [comment]
Besides `idom.app` I'd say `idom.compat` would be my next pick.

**Comment by rmorshea** [comment]
Actually, didn't see `idom.backend` - that one's pretty good.

**Comment by Archmonger** [comment]
Agreed. Semantically, `idom.backend` does make a lot of sense. I'll sit on this one for a bit and see if I think of any other options.
