### ISSUE TITLE
Indicate Reconnection Status

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#761]
### Current Situation

Presently, we do not indicate to the user that the app has lost connection with the server.

### Proposed Actions

We should have some non-intrusive modal in a corner of that app which indicates whether the server has disconnected and when it will reconnect next.

**Comment by Archmonger** [comment]
I disagree. The IDOM framework should not inject a modal. There should be some sort of event API for the user to display pre-rendered HTML upon disconnect.

**Comment by rmorshea** [comment]
Ah, yes. I forgot about that one. That's definitely the way to go.
