### ISSUE TITLE
html_to_vdom breaks on whitespaces and null HTML tags

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#777]
### Current Situation

If a HTML string has ...

- Additional whitespace at the tail of the HTML document
- A null (non-terminated) HTML tag such as `<hr>` within the document

... then `html_to_vdom` will silently fail without raising an exception

See [my Django IDOM PR](https://github.com/idom-team/django-idom/pull/81) for how I caused the `script` tag issue to occur at [this LOC](https://github.com/Archmonger/django-idom/blob/1dda52d01022cca47da25610c2cf97a45c6a34d3/tests/test_app/components.py#L144).

### Proposed Actions

Whitespace issue can be fixed by simple regex and/or using `str.strip()`.

Script tag issue needs further investigation. This might open up a can of worms to test `html_to_vdom` with all `idom.html` types.

**Comment by Archmonger** [comment]
@rmorshea Would like you to chime in on this one too, while you still have availability.

**Comment by rmorshea** [comment]
I'll take a look at this over the weekend.

**Comment by Archmonger** [comment]
The issue I categorized as a "script tag" issue appears to be that XHTML style tags that don't have end tags (such as `<br>` break the HTMLParser implementation that is currently developed. I am looking into a solution.

**Comment by Archmonger** [comment]
There doesn't appear to be a fool proof way of resolving this with python's built-in `HtmlParser`. It's technically a syntax tree generator and not a DOM tree generator, so I'm going to switch us to using [`lxml`](https://lxml.de/tutorial.html). A nice benefit of the switch is it technically should be much faster.

**Comment by rmorshea** [comment]
That [target parser interface](https://lxml.de/parsing.html#the-target-parser-interface) of `lxml` seems like it maps nicely onto what we already do. I wasn't able to find something quite as simple in `bs4`, but I didn't look that hard.

**Comment by Archmonger** [comment]
Using that interface would likely make us fall into the same pitfalls, since it doesn't provide access to the DOM tree. I've been testing out performing these transformations recursively. 

```python
from io import StringIO
from pprint import pprint

from lxml import etree

my_html = """
<div id="view_to_component_middleware">
    view_to_component_middleware: Success
    <div class="inner"> this is text </div>
</div>\n

<hr>
<script>
    var dog = 'memes';
</script>"""
parser = etree.HTMLParser()
tree = etree.parse(StringIO(my_html), parser)
root = tree.getroot()


def _set_if_val_exists(object, key, value):
    """Sets a key on a dictionary if the value's length is greater than 0."""
    if len(value):
        object[key] = value


def html_to_dict(node, *transforms):
    """Convert an lxml.etree node tree into a VDOM dict."""
    result = {"tagName": node.tag}
    _set_if_val_exists(result, "attributes", dict(node.items()))
    _set_if_val_exists(
        result, "children", [html_to_dict(child) for child in node.iterchildren()]
    )

    for transform in transforms:
        result = transform(result)

    return result


pprint(html_to_dict(root))
```

Seems to work solid so far, and is a lot more readable.
