### ISSUE TITLE
Accidental mutation of old model causes invalid JSON Patch

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#801]
### Current Situation

Unfortunately, the monkey patch applied to `jsonpatch` doesn't seem to have really fixed the problem. I don't believe that we'll be able to resolve [this issue](https://github.com/stefankoegl/python-json-patch/issues/138#issuecomment-1212994774) and, even if we were, the library doesn't really seem to be maintained.

### Proposed Actions

Instead of actually computing a diff, just use a `replace` operation where the value is the new render. This will probably have a performance cost in cases where network latency dominates. The alternative though, is getting an error on occasion when JSON patch fails to generate a correct diff.

**Comment by rmorshea** [comment]
This issue was discovered to still exist while working with [this test component](https://github.com/idom-team/django-idom/blob/093fc368fe974d0ee17b9c8a55169c2b6042b20e/tests/test_app/components.py#L157-L192).

**Comment by rmorshea** [comment]
Turns out, the invalid JSON patch was produced because I was [mutating something](https://github.com/idom-team/idom/blob/f593ee3067cac004ca07e4c8378f87f8c45341f3/src/idom/core/layout.py#L234-L236) I shouldn't have been.

**Comment by Archmonger** [comment]
Will we be sticking to using `jsonpatch` then, or are there additional critical bugs in the library?

**Comment by rmorshea** [comment]
The issue I posted there is still valid, but the fix I posted for it appears to work so I don't think we need to drop `jsonpatch` in a hurry.

**Comment by rmorshea** [comment]
I still think we should plan to remove it eventually though.
