### ISSUE TITLE
VDOM cannot be rendered after a component

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#806]
### Current Situation

`v0.40.0` brought a regression where VDOM elements cannot be rendered following a component.

For example, `Text 2` is never rendered in the following scenario:

```python
from idom import component, html, run


@component
def Test():
    return html.div("Hello World!")


@component
def App():
    return html.div(
        html.h1("Text 1"),
        Test(),
        html.h1("Text 2"),
    )

run(App)
```

### Proposed Actions

This is a pretty major breaking bug, and needs to be resolved ASAP.

I personally would also yank the `v0.40.0` release as it has been roughly a month of unusably broken behavior.

**Comment by rmorshea** [comment]
I've got an idea on how to bypass the issues with JSON patch. Will try to get to this over the weekend.

**Comment by rmorshea** [comment]
Version has also been yanked.
