### ISSUE TITLE
Fix example from Documentation in Section 5

### ISSUE THREAD

**Issue by jvfei** [idom-team/idom#813]
### Current Situation

copy and pasted first name, so where it should say last name and email is incorrect. https://idom-docs.herokuapp.com/docs/guides/adding-interactivity/index.html#section-5-dangers-of-mutability

### Proposed Actions

correct the example

**Comment by Archmonger** [comment]
@jvfei Would you like to contribute a PR to resolve this? Would need to change [this file](https://github.com/idom-team/idom/blob/3f8803e1266e8cdb05ee8d7fec572c47f3cb6a50/docs/source/guides/adding-interactivity/dangers-of-mutability/_examples/dict_update.py).
