### ISSUE TITLE
Deprecate `module_from_template`

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#822]
### Discussed in https://github.com/idom-team/idom/discussions/821

<div type='discussions-op-text'>

<sup>Originally posted by **Archmonger** October 18, 2022</sup>
While the ability to load JavaScript modules from NPM on the fly is clever, it technologically isn't possible to do properly.

That is due to ReactJS version mismatches, which frequently pop up when using this API.

For the health of this framework, I would recommend we deprecate `module_from_template` and double-down on _JavaScript Components API_ docs to supplement this.</div>

**Comment by rmorshea** [comment]
Closed by: https://github.com/idom-team/idom/commit/8f3785bad50935d77de61c4f94c6cd4fc25aeadc
