### ISSUE TITLE
Remove Unused Arg

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#856]
### Current Situation

There's an unused argument [here](https://github.com/idom-team/idom/blob/1e3fac1e4227ac3d5ff225970c95e0e6acfef6ff/src/idom/core/events.py#L135).

### Proposed Actions

Remove it.

**Comment by Archmonger** [comment]
Did you reference the wrong LOC?

Seems to me that `positional_args=...` is not an unused arg.

**Comment by rmorshea** [comment]
That is correct. Closing.
