### ISSUE TITLE
Rename "IDOM" to "ReactPy"

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#888]
### Current Situation

This issue exists to track our rename efforts

**Comment by Archmonger** [comment]
We might we want a separate PR to #892

For `idom=1.0.0`, we probably want to `print()` a warning saying that the package has been renamed to `reactpy`

**Comment by rmorshea** [comment]
I'm thinking we 1.0 release IDOM (without the warning) then create an `idom` branch for posterity. We then execute the rename on `main` and move the repo. We then release ReactPy (once we're ready) after which we release a 1.0.1 version of IDOM with the warning using the `idom` branch.

**Comment by Archmonger** [comment]
LGMT

**Comment by rmorshea** [comment]
We good to release idom 1.0 now you think?

**Comment by Archmonger** [comment]
Yep, I'll push a Django-IDOM release as well.
